// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9ztovl_uk19IQe1uVMQ5HDlNMLq8UUls',
    appId: '1:871393852406:web:9f33543f518be270ad65d7',
    messagingSenderId: '871393852406',
    projectId: 'english-app-5110d',
    authDomain: 'english-app-5110d.firebaseapp.com',
    storageBucket: 'english-app-5110d.firebasestorage.app',
    measurementId: 'G-9W71M89Q0H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtA_4bXPXpXqSYYsgaY-7F6ropiihUaWI',
    appId: '1:871393852406:android:ef0dcfbb2045e331ad65d7',
    messagingSenderId: '871393852406',
    projectId: 'english-app-5110d',
    storageBucket: 'english-app-5110d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFXSzM9Yn7YSGmjpS5OF0TvQEcremQFR8',
    appId: '1:871393852406:ios:e2996df5b14b4058ad65d7',
    messagingSenderId: '871393852406',
    projectId: 'english-app-5110d',
    storageBucket: 'english-app-5110d.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFXSzM9Yn7YSGmjpS5OF0TvQEcremQFR8',
    appId: '1:871393852406:ios:e2996df5b14b4058ad65d7',
    messagingSenderId: '871393852406',
    projectId: 'english-app-5110d',
    storageBucket: 'english-app-5110d.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9ztovl_uk19IQe1uVMQ5HDlNMLq8UUls',
    appId: '1:871393852406:web:235dc45492a7f910ad65d7',
    messagingSenderId: '871393852406',
    projectId: 'english-app-5110d',
    authDomain: 'english-app-5110d.firebaseapp.com',
    storageBucket: 'english-app-5110d.firebasestorage.app',
    measurementId: 'G-G14XGS3Y3Z',
  );
}
